#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Memini is a simple project that creates vocabulary grids to train.
# Copyright 2019 Nicolas Hainaux <nh.techn@gmail.com>

# This file is part of Memini.

# Memini is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# any later version.

# Memini is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with Memini; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

import toml

with open('./pyproject.toml', 'r') as f:
    pp = toml.load(f)

with open('./memini/data/metadata.toml', 'w') as f:
    toml.dump({'__version__': pp['tool']['poetry']['version'],
               '__myname__': pp['tool']['poetry']['name'],
               '__authors__': pp['tool']['poetry']['authors']},
              f)
