sudo: required
dist: bionic
language: python
python:
    - "3.6"
# cache:
#     - pip3
# blocklist
# branches:
#   except:
#   - broken
before_install:
  - sudo apt-get -qq update
  - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py > ../get-poetry.py
  - sudo python ../get-poetry.py
install:
    - "poetry install"
script:
    - "coverage run --source=vocashaker -m pytest -x -vv"
after_success:
    coveralls
